(() => {
  'use strict';
  try {
    const params = new URLSearchParams(location.search);
    if (params.get('debug') !== '1' || params.get('diag') !== '1') return;
    if (params.get('diagthrow') === '1') throw new Error('intentional diagnostic self-test');

    const state = { events: [], snapshots: [], counters: { renderOraclePhrase: 0, renderOrbText: 0, typeStart: 0, typeComplete: 0 }, traces: [] };
    const safe = (fn, fallback = null) => { try { return fn(); } catch (error) { console.error('[ALX DIAG]', error); return fallback; } };
    const rect = (el) => safe(() => { const r = el.getBoundingClientRect(); return { x:r.x, y:r.y, top:r.top, left:r.left, right:r.right, bottom:r.bottom, width:r.width, height:r.height }; });
    const css = (el, pseudo = null) => safe(() => { const s = getComputedStyle(el, pseudo); return { content:s.content, display:s.display, visibility:s.visibility, opacity:s.opacity, zIndex:s.zIndex, position:s.position, transform:s.transform, filter:s.filter }; });
    const textOf = (el) => safe(() => ({ tagName:el.tagName, id:el.id || '', className:typeof el.className === 'string' ? el.className : '', innerText:(el.innerText || '').trim(), textContent:(el.textContent || '').trim(), childElementCount:el.childElementCount, style:css(el), rect:rect(el) }), null);
    const visibleTextSources = () => safe(() => [...document.querySelectorAll('*')].map(textOf).filter((x) => x && (x.innerText || x.textContent) && x.rect && x.rect.width > 0 && x.rect.height > 0 && x.style.display !== 'none' && x.style.visibility !== 'hidden' && x.style.opacity !== '0'), []);
    const pseudo = (selector) => safe(() => { const el = document.querySelector(selector); return { selector, before:css(el,'::before'), after:css(el,'::after') }; }, { selector, before:null, after:null });
    const media = () => safe(() => [...document.querySelectorAll('canvas,svg,iframe')].map((el) => ({ tagName:el.tagName, id:el.id || '', className:typeof el.className === 'string' ? el.className : '', rect:rect(el), style:css(el) })), []);
    const shadow = () => safe(() => [...document.querySelectorAll('*')].filter((el) => !!el.shadowRoot).map((el) => ({ tagName:el.tagName, id:el.id || '', className:typeof el.className === 'string' ? el.className : '' })), []);
    const snapshot = (label) => { const report = collect(); report.snapshotLabel = label; report.timestamp = Date.now(); state.snapshots.push(report); render(); return report; };
    const trace = (event, payload = {}) => { state.traces.push({ event, timestamp:Date.now(), ...payload }); state.events.push({ event, timestamp:Date.now(), ...payload }); if (event === 'renderOraclePhrase') state.counters.renderOraclePhrase++; if (event === 'renderOrbText') state.counters.renderOrbText++; if (event === 'TYPE START') state.counters.typeStart++; if (event === 'TYPE COMPLETE') state.counters.typeComplete++; render(); };
    const collect = () => ({ runtime:{ userAgent:navigator.userAgent, devicePixelRatio:window.devicePixelRatio, telegram:window.Telegram?.WebApp ? { version:window.Telegram.WebApp.version || null, platform:window.Telegram.WebApp.platform || null } : null }, counters:state.counters, traces:state.traces.slice(-100), events:state.events.slice(-100), dom:{ oraclePhraseCount:document.querySelectorAll('.oracle-phrase').length, mixNameCount:document.querySelectorAll('.mix-name').length, mixDescCount:document.querySelectorAll('.mix-desc').length, screenContentChildren:document.querySelector('#screenContent')?.children.length ?? null }, visibleTextSources:visibleTextSources(), pseudo:['.screen','.screen-content','.oracle-phrase','.mix-name','.mix-desc','.orb','.orb-frame','.orb-wrap','.stage'].map(pseudo), media:media(), shadowRoots:shadow(), snapshots:state.snapshots.slice(-10) });
    window.ALX_DIAG = { snapshot, trace, lifecycle:(event,payload={}) => trace(event,payload), getReport:collect, onTypeStart:(sceneId,label) => trace('TYPE START',{sceneId,label}), onTypeComplete:(sceneId,label) => trace('TYPE COMPLETE',{sceneId,label}), onTypeAbort:(sceneId,label) => trace('TYPE ABORT',{sceneId,label}) };

    const addStyles = () => safe(() => { const s=document.createElement('style'); s.textContent='#alx-diagnostic-panel{position:fixed;z-index:2147483647;left:8px;right:8px;bottom:8px;max-height:48vh;display:flex;flex-direction:column;gap:6px;padding:10px;color:#f6ecd7;background:rgba(8,6,15,.96);border:2px solid #e3bd71;border-radius:12px;font:12px/1.35 ui-monospace,monospace}#alx-diagnostic-panel button{min-height:38px;color:#120d1e;background:#e3bd71;border:0;border-radius:8px;font-weight:700}#alx-diagnostic-report{margin:0;max-height:32vh;overflow:auto;white-space:pre-wrap;word-break:break-word}'; document.head.appendChild(s); });
    let reportEl;
    const render = () => { if (reportEl) safe(() => { reportEl.textContent = JSON.stringify(collect(), null, 2); }); };
    const start = () => safe(() => { addStyles(); const panel=document.createElement('aside'); panel.id='alx-diagnostic-panel'; panel.innerHTML='<strong>ALX FORENSICS · PASSIVE</strong><pre id="alx-diagnostic-report"></pre><button id="alx-diagnostic-hide" type="button">HIDE PHRASE</button><button id="alx-diagnostic-copy" type="button">COPY DIAGNOSTICS</button>'; document.body.appendChild(panel); reportEl=panel.querySelector('#alx-diagnostic-report'); panel.querySelector('#alx-diagnostic-hide').addEventListener('click',()=>safe(()=>{const p=document.querySelector('.oracle-phrase');if(p)p.style.visibility='hidden';})); panel.querySelector('#alx-diagnostic-copy').addEventListener('click',()=>safe(async()=>{try{await navigator.clipboard.writeText(reportEl.textContent);}catch(error){console.error('[ALX DIAG]',error);}})); snapshot('DIAGNOSTIC_READY'); });
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start, { once:true }); else start();
  } catch (error) { console.error('[ALX DIAG]', error); }
})();
